### ISSUE TITLE
The module no longer compiles in the latest version of AzerothCore

### ISSUE THREAD

**Issue by kambire** [azerothcore/mod-azerothshard#25]
The module no longer compiles in the latest version of AzerothCore

**Comment by pangolp** [comment]
The idea of this module is not that it is compatible with the latest version. Many of the modules used here are being worked on independently today and are up to date. I don't know if everyone, but the vast majority. We try to update it to make it compatible, but the changes are many and it's really better to work each module independently.

**Comment by Helias** [comment]
the idea is to extract all the modules of this repo into different repositories like we did for https://github.com/azerothcore/mod-arena-3v3-solo-queue/

**Comment by kambire** [comment]
> The idea of this module is not that it is compatible with the latest version. Many of the modules used here are being worked on independently today and are up to date. I don't know if everyone, but the vast majority. We try to update it to make it compatible, but the changes are many and it's really better to work each module independently.

hola gracias por la respuesta con mi pocos y casi nulos conocimientos estoy tratando de ir arreglando en cuento van saliendo los errores al compilar pero se me complica, en caso que pueda compilar y funcione puedo pasar las modificaciones, pero lastimosamente entre yo que soy malo y la IA que es peor que yo se nos vuelve un trabajo largo.
