### ISSUE TITLE
ExtraDatabase compilation error

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/mod-azerothshard#3]
After the latest changes from @Winfidonarleyan to the database system, our ExtraDatabase implementation is not working anymore.
Hence, I had to disable some of the functions:

Cannot define AddDatabase method https://github.com/azerothcore/mod-azerothshard/blob/master/modules/mod-as-common/src/game/ExtraDatabase.cpp#L39 , that should be used here: https://github.com/azerothcore/mod-azerothshard/blob/master/modules/mod-as-common/src/plugins/AzthWorldScript.cpp#L16

We should be able to define custom new database connections inside a module

## Compilation error

```
/ExtraDatabase.cpp:40:33: error: explicit instantiation of undefined function template 'AddDatabase'
DatabaseLoader& DatabaseLoader::AddDatabase<ExtraDatabaseConnection>(DatabaseWorkerPool<ExtraDatabaseConnection>&, std::string const&);
                                ^
azerothcore-wotlk/src/server/database/Database/DatabaseLoader.h:27:21: note: explicit instantiation refers here
    DatabaseLoader& AddDatabase(DatabaseWorkerPool<T>& pool, std::string const& name);
```

## How to test:

Just uncomment those lines and recompile the core to check the error

**Comment by Yehonal** [comment]
@Winfidonarleyan can you have a look at it, please?

**Comment by Winfidonarleyan** [comment]
Can add permissions for this repo? I correct this

**Comment by Yehonal** [comment]
Done! try again

**Comment by Yehonal** [comment]
https://github.com/azerothcore/mod-azerothshard/pull/5
